### PR TITLE
Fix some dialyzer warnings; add type t to UploadedImage

### LINKED ISSUE #34: upload return type is incorrect
On this line: 

https://github.com/smeevil/cloudex/blob/fa1e09b247068214975a67b673f17f74f7edc745/lib/cloudex.ex#L19

We return an `%Cloudex.UploadedImage{}` when there's only one item.

I do think there may be some deeper issues here, too. For example, the `Enum.count(result)` is operating on `upload_results ++ invalid_list`.

### PR DESCRIPTION
**Pull request by joshsmith**
- Fixes some dialyzer errors
- Adds a `t` for documenting the `%Cloudex.UploadedImage{}` struct
- A tiny bit of formatting

Fixes #34

### CODE REVIEW

**Comment by joshsmith** [comment]
@smeevil I am happy to accommodate any feedback.

**Comment by joshsmith** [comment]
The build failed solely because of a Coveralls reporting timeout.

**Comment by smeevil** [comment]
Awesome, thanks !

**Comment by smeevil** [comment]
1.0.1 is now published

**Comment by joshsmith** [comment]
Thank you!

**Pull request merged**
